//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteData
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int count = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int cover = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int drop_shadow = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int frame1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int frame_b = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int input = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int left_button = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int left_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int left_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int left_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int middle_button = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int middle_focused = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int middle_normal = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int middle_pressed = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int pic_frame_grey = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int pic_frame_white = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int right_button = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int right_focused = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int right_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int right_pressed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int shadow_layer = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int tw_favs = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int tw_favs_b = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int tw_search = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int tw_search_b = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int tweet_frame_ds = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int twitter_logo = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int white_border = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int white_fill = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int white_fill_black_border = 2130837534;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000e
			public const int btnL = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int btnM = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int btnR = 2131034129;
			
			// aapt resource value: 0x7f05000c
			public const int etUser = 2131034124;
			
			// aapt resource value: 0x7f050000
			public const int fav_list = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int ibFavs = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int ibNew = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int iv = 2131034123;
			
			// aapt resource value: 0x7f050012
			public const int ivProfile = 2131034130;
			
			// aapt resource value: 0x7f050002
			public const int ivProfileH = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout1 = 2131034113;
			
			// aapt resource value: 0x7f050015
			public const int linearLayout2 = 2131034133;
			
			// aapt resource value: 0x7f050003
			public const int linearLayout3 = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int list = 2131034120;
			
			// aapt resource value: 0x7f05000d
			public const int myButton = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int tv1 = 2131034127;
			
			// aapt resource value: 0x7f05000a
			public const int tvDate = 2131034122;
			
			// aapt resource value: 0x7f050013
			public const int tvName = 2131034131;
			
			// aapt resource value: 0x7f050004
			public const int tvNameH = 2131034116;
			
			// aapt resource value: 0x7f050014
			public const int tvScreenName = 2131034132;
			
			// aapt resource value: 0x7f050005
			public const int tvScreenNameH = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int tvTweet = 2131034121;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int fav_list = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int list = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int list_tweet = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int tweet_display = 2130903044;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
